# Generated by Django 3.2.9 on 2021-12-06 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_auto_20211206_1510'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='slug',
            new_name='subcategory_slug',
        ),
    ]
