# Generated by Django 3.2.9 on 2021-12-07 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_alter_category_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='category_banner/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='subcategory_slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
    ]
