# Generated by Django 3.1.4 on 2022-01-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_auto_20211207_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_customer',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
