# Generated by Django 3.2.9 on 2022-02-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_member_mimage'),
        ('ecommerce', '0011_auto_20220129_1631'),
    ]

    operations = [
    ]
