# Generated by Django 3.2.9 on 2022-01-17 11:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
